// 12 POs received on 2026-08-03 (a single batch-receiving session, ledger timestamps
// 10:34:56-10:39:53) have a valid inventoryLedger 'purchase_received' entry (physical
// stock genuinely arrived) but NO corresponding "Penerimaan Barang" journal was ever
// created - likely a partial write failure in that receiving session (6 sibling POs from
// the same session/minute did get their journal correctly, e.g. JU2608030031-037).
// This creates the missing journals using the exact schema of the sibling journals that
// succeeded (Dr 1201 Inventory On Hand / Cr 1203 Inventory in Transit, sourceDocument:
// 'PO_RECEIPT', isAutoGenerated: true), dated 2026-08-03 to match.
//
// Usage:
//   node fix_missing_receipt_journals.cjs            (dry-run, no writes)
//   node fix_missing_receipt_journals.cjs --apply     (actually writes)

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore, Timestamp } = require('firebase-admin/firestore');
const serviceAccount = require('/Users/Felixsalim/gen-lang-client-0501656267-firebase-adminsdk-fbsvc-35d61d1f5a.json');
const app = initializeApp({ credential: cert(serviceAccount), projectId: 'gen-lang-client-0501656267' });
const db = getFirestore(app, 'ai-studio-53e52a01-a8d6-4019-9f99-16eb3032e0f7');

const APPLY = process.argv.includes('--apply');

function toDate(ts) {
  if (!ts) return new Date(0);
  if (typeof ts.toDate === 'function') return ts.toDate();
  if (typeof ts.seconds === 'number') return new Date(ts.seconds * 1000);
  return new Date(ts);
}

const MISSING_CODES = ['PO26072705', 'PO26072703', 'PO26072910', 'PO26072805', 'PO26072904', 'PO26072704', 'PO26072803', 'PO26072701', 'PO26072708', 'PO26072807', 'PO26072810', 'PO26072913'];

async function main() {
  console.log(APPLY ? '*** MODE: APPLY ***' : '*** MODE: DRY-RUN ***');

  const [ledgerSnap, poSnap, journalSnap] = await Promise.all([
    db.collection('inventoryLedger').get(),
    db.collection('purchaseOrders').get(),
    db.collection('journalEntries').get(),
  ]);
  const ledger = ledgerSnap.docs.map(d => ({ id: d.id, ...d.data() }));
  const pos = poSnap.docs.map(d => ({ id: d.id, ...d.data() }));
  const poByCode = new Map(pos.map(p => [p.purchaseCode, p]));
  const existingJU260803Numbers = journalSnap.docs.map(d => d.id).filter(id => id.startsWith('JU2608030')).map(id => parseInt(id.slice(8), 10));
  let nextNum = Math.max(...existingJU260803Numbers) + 1;

  const toCreate = [];
  for (const code of MISSING_CODES) {
    const po = poByCode.get(code);
    if (!po) { console.error('SAFETY ABORT: PO tidak ketemu', code); process.exit(1); }
    const alreadyHasJournal = journalSnap.docs.some(d => d.data().sourceId === po.id && (d.data().description || '').includes('Penerimaan Barang'));
    if (alreadyHasJournal) { console.error('SAFETY ABORT: PO ini sudah punya jurnal, jangan dobel:', code); process.exit(1); }

    const entries = ledger.filter(e => e.refId === po.id && e.type === 'purchase_received' && e.reversed !== true);
    if (entries.length === 0) { console.error('SAFETY ABORT: tidak ada ledger entry untuk', code); process.exit(1); }
    const totalCents = entries.reduce((a, e) => a + (e.qtyDelta || 0) * (e.unitCost || 0), 0);
    const latestTs = entries.reduce((max, e) => { const d = toDate(e.timestamp); return d > max ? d : max; }, new Date(0));

    const id = `JU2608030${String(nextNum).padStart(3, '0')}`;
    nextNum++;

    const journalEntry = {
      date: '2026-08-03',
      description: `PO #${code}\nPenerimaan Barang`,
      lines: [
        { accountCode: '1201', account: 'Inventory On Hand', debit: totalCents, credit: 0 },
        { accountCode: '1203', account: 'Inventory in Transit', debit: 0, credit: totalCents },
      ],
      sourceDocument: 'PO_RECEIPT',
      sourceId: po.id,
      createdAt: Timestamp.fromDate(latestTs),
      createdBy: 'felixsalimzz@gmail.com',
      isAutoGenerated: true,
      note: 'Dibuat ulang via audit rekonsiliasi 2026-08 - jurnal asli gagal terbuat saat sesi terima barang 2026-08-03 walau ledger sudah tercatat.',
    };

    console.log(`\n${id} <- ${code} | value=${(totalCents / 100).toFixed(2)} NTD | ${entries.length} ledger entries | latestTs=${latestTs.toISOString()}`);
    toCreate.push({ id, journalEntry });
  }

  const totalValue = toCreate.reduce((a, c) => a + c.journalEntry.lines[0].debit, 0) / 100;
  console.log(`\nTotal jurnal yang akan dibuat: ${toCreate.length}, total nilai: ${totalValue.toFixed(2)} NTD`);

  if (!APPLY) {
    console.log('\nDry-run selesai. Tidak ada perubahan ditulis. Jalankan ulang dengan --apply untuk benar-benar menulis.');
    return;
  }

  const batch = db.batch();
  toCreate.forEach(c => batch.set(db.collection('journalEntries').doc(c.id), c.journalEntry));
  await batch.commit();
  console.log('Selesai.');
}

main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
